- hosts: imageservers
  become: yes
  gather_facts: no
  tasks:
    - apt: name=python3-selinux state=present update_cache=true
    - service: name=apparmor enabled=no state=stopped
    - apt: 
        name:
          - git 
          - gcc 
          - patch 
          - autoconf 
          - automake 
          - bison 
          - build-essential
          - libssl-dev 
          - libyaml-dev 
          - libreadline6-dev 
          - zlib1g-dev 
          - libncurses5-dev 
          - libffi-dev 
          - libgdbm6 
          - libgdbm-dev 
          - libmysqlclient-dev 
          - libcurl4-openssl-dev 
          - libjpeg-turbo8 
          - libjpeg-turbo8-dev 
          - libpng16-16
          - libpng-dev 
          - libmcrypt4 
          - libmcrypt-dev 
          - libtidy5deb1
          - libtidy-dev 
          - libxml2-dev 
          - libxslt1-dev 
          - readline-common 
          - re2c 
          - language-pack-ja
          - libbz2-dev
          - curl
          - pkg-config
          - libsqlite3-dev
          - libonig-dev
          - libzip-dev
        state: present
