- hosts: imageservers
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
        force=yes
    # https://twitter.com/matsuu/status/773105183744069633
    - replace: dest=/home/isucon/.xbuild/perl-install regexp='http://cpanmin\.us/' replace='http://git.io/cpanm'
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 3.3.5 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    # node
    - command: /home/isucon/.xbuild/node-install v20.9.0 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
    # perl
    - command: /home/isucon/.xbuild/perl-install 5.20.2 /home/isucon/.local/perl
      args:
        creates: /home/isucon/.local/perl/bin/perl
    # php
    - command: /home/isucon/.xbuild/php-install 8.3.10 /home/isucon/.local/php -- --with-pear --with-openssl
      args:
        creates: /home/isucon/.local/php/bin/php
    - copy: src=../files/php.ini dest=/home/isucon/.local/php/etc/php.ini owner=isucon mode=644
    # golang
    - command: /home/isucon/.xbuild/go-install 1.20 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go
    # scala
    - shell: curl https://downloads.lightbend.com/scala/2.13.15/scala-2.13.15.tgz | (cd /home/isucon/.local && tar xzf -)
      args:
        creates: /home/isucon/.local/scala-2.13.15/bin/scala
    - file: src=/home/isucon/.local/scala-2.13.15 dest=/home/isucon/.local/scala state=link

- hosts: imageservers
  become: yes
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
